In [1]:
import numpy as np

arr=np.arange(10)
arr.resize(4,2)

arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [2]:
arr[1,1]

3

In [3]:
arr[3,:] # first row every element

array([6, 7])

In [4]:
a= arr[:,0] # first column every element

a

a[0]

0

In [5]:
a= arr[:,:-1]  #first column - every element as a seperate array

a
a[0]

array([0])

In [6]:
arr_i = np.array([[0,1],[0,1],[1,0],[1,0]], dtype=bool)
arr_i

array([[False,  True],
       [False,  True],
       [ True, False],
       [ True, False]])

In [7]:
arr[arr_i]=100 # replace with 100 where arr_i is True

arr

array([[  0, 100],
       [  2, 100],
       [100,   5],
       [100,   7]])

In [8]:
arr_b= arr+1
arr_b

array([[  1, 101],
       [  3, 101],
       [101,   6],
       [101,   8]])

In [9]:
arr+arr_b

array([[  1, 201],
       [  5, 201],
       [201,  11],
       [201,  15]])

In [10]:
arr_c= arr*2
arr_c

array([[  0, 200],
       [  4, 200],
       [200,  10],
       [200,  14]])

In [11]:
arr_c*arr

array([[    0, 20000],
       [    8, 20000],
       [20000,    50],
       [20000,    98]])

In [12]:
arr_c-arr_b

array([[-1, 99],
       [ 1, 99],
       [99,  4],
       [99,  6]])

In [13]:
arr_c/arr_b

array([[0.        , 1.98019802],
       [1.33333333, 1.98019802],
       [1.98019802, 1.66666667],
       [1.98019802, 1.75      ]])

In [14]:
arr_c>20

array([[False,  True],
       [False,  True],
       [ True, False],
       [ True, False]])